export const placeData = [
  {
    id: "1",
    label: "THẮNG CẢNH",
    image: "/Images/adventurePage/adventurePage1.jpg",
    banner: "/Images/pageBanner/placeDetailBanner.jpg",
    title: "Hoàng Su Phì",
    description:
      "Tại Hoàng Su Phì ruộng bậc thang bắc lên tận mây trời, lác đác xen các thửa ruộng vàng óng là những mái nhà nhỏ nhắn của bà con dân tộc ẩn trong lùm cây.",
    like: " 12.5K",
    share: " 1.7K",
    review: "350",
    score: "8.9",
    price: "3,790,000",
  },
  {
    id: "2",
    label: "DANH LAM",
    image: "/Images/adventurePage/adventurePage2.jpg",
    banner: "/Images/pageBanner/tourDetailBanner.jpg",
    title: "Đèo Mã Pí Lèng",
    description:
      "Đèo Mã Pí Lèng nằm trên con đường Hạnh Phúc nối liền Đồng Văn và Mèo Vạc. Đây được biết đến là cung đường đẹp nhất vùng cao nguyên đá.",
    like: " 13.5K",
    share: " 1.2K",
    review: "310",
    score: "8.0",
    price: "3,790,000",
  },
  {
    id: "3",
    label: "BẢO TÀNG",
    image: "/Images/adventurePage/adventurePage3.jpg",
    banner: "/Images/pageBanner/hotelDetailBanner.jpg",
    title: "Cao nguyên đá Đồng Văn",
    description:
      "Cao nguyên đá Đồng Văn là địa danh không còn xa lạ chút nào đối với tất cả người dân Việt Nam. Nếu đến Hà Giang mà bạn không đến thăm công viên địa chất nổi tiếng trên toàn thế giới này thì quả là một điều quá phí hoài.",
    like: " 4.5K",
    share: " 1K",
    review: "260",
    score: "9.0",
    price: "3,790,000",
  },
  {
    id: "4",
    label: "THẮNG CẢNH",
    image: "/Images/adventurePage/adventurePage4.jpg",
    banner: "/Images/pageBanner/restaurantDetailBanner.jpg",
    title: "Thung lũng Sủng Là",
    description:
      "Sủng Là được biết đến như một trong những địa điểm du lịch Hà Giang nổi tiếng với các vườn hoa khoe sắc. Thung lũng Sủng Là là bông hoa giữa cao nguyên đá, cuốn hút du khách bởi vẻ đẹp mộc mạc.",
    like: " 5.5K",
    share: " 2.7K",
    review: "50",
    score: "7.0",
    price: "3,790,000",
  },
  {
    id: "5",
    label: "DANH LAM",
    image: "/Images/adventurePage/adventurePage5.jpg",
    banner: "/Images/pageBanner/productDetailBanner.jpg",
    title: "Dinh Thự họ Vương – dinh thự vua Mèo",
    description:
      "Dinh thự họ Vương nằm trên đỉnh một quả đồi nhỏ, nơi đây cửa vào có hàng cây samu cổ thụ, thẳng tắp. Dinh thự mang kiến trúc độc đáo, có sự ảnh hưởng của ba nền kiến trúc: Trung Quốc, người dân tộc Mông và Pháp.",
    like: " 18.5K",
    share: " 1.4K",
    review: "300",
    score: "8.5",
    price: "3,790,000",
  },
  {
    id: "6",
    label: "DI TÍCH LỊCH SỬ",
    image: "/Images/adventurePage/adventurePage6.jpg",
    banner: "/Images/pageBanner/placeDetailBanner.jpg",
    title: "Phó Bảng – Yên Minh",
    description:
      "Phó Bảng là nơi có những ngôi nhà cổ với kiến trúc độc đáo. Những thửa ruộng nằm cạnh hai bên đường đi ở Phó Bảng ngập tràn hoa tam giác mạch.",
    like: "7.5K",
    share: "700",
    review: "90",
    score: "8.0",
    price: "3,790,000",
  },
];

export const tourData = [
  {
    id: "1",
    label: "TRỌN GÓI",
    image: "/Images/tourPage/tourPage1.jpg",
    banner: "/Images/pageBanner/tourDetailBanner.jpg",
    title: "Tour khám phá Hà Giang - Nho Quế hùng vĩ 3 ngày 2 đêm",
    description: "Tự hào là nhà tổ chức tour Hà Giang chất lượng số 1 trên thị trường. Hãy đồng hành cùng PYS Travel để có một chuyến đi ấn tượng, vui vẻ, an toàn và đáng nhớ! Mùa xuân Hà Giang là sắc đào sắc mận nở trắng trời, mùa thu là những thửa ruộng bậc thang vàng óng ả, và khi mùa đông đến cả Hà Giang lại chìm trong sắc hồng dịu ngọt của những cánh đồng tam giác mạch mênh mang nơi miền biên viễn.",
    tourCode: "NDHAN200-006-260522XE-V",
    startingGate: "Hà Nội",
    price: "3,790,000",
    startTime: "26/05/2022",
    period: {
      days: "4",
      nights: "3",
    },
    review: "300",
    score: "8.9",
    subtitle: "3 ngày 2 đêm",
    href: "tour-detail",
  },
  {
    id: "2",
    label: "GIA ĐÌNH",
    image: "/Images/tourPage/tourPage2.jpg",
    banner: "/Images/pageBanner/hotelDetailBanner.jpg",
    title: "Du lịch Miền Bắc Hà Nội - Hà Giang - Lũng Cú - Cao Bằng",
    description: "Tự hào là nhà tổ chức tour Hà Giang chất lượng số 1 trên thị trường. Hãy đồng hành cùng PYS Travel để có một chuyến đi ấn tượng, vui vẻ, an toàn và đáng nhớ! Mùa xuân Hà Giang là sắc đào sắc mận nở trắng trời, mùa thu là những thửa ruộng bậc thang vàng óng ả, và khi mùa đông đến cả Hà Giang lại chìm trong sắc hồng dịu ngọt của những cánh đồng tam giác mạch mênh mang nơi miền biên viễn.",
    tourCode: "NDHAN200-006-260522XE-V",
    startingGate: "Hà Nội",
    price: " 2,990,000",
    startTime: "27/05/2022",
    period: {
      days: "4",
      nights: "3",
    },
    review: "350",
    score: "7.9",
    subtitle: "4 ngày 3 đêm",
    href: "tour-detail",
  },
  {
    id: "3",
    label: "TRỌN GÓI",
    image: "/Images/tourPage/tourPage3.jpg",
    banner: "/Images/pageBannerrestaurantDetailBanner.jpg",
    title: "Du lịch Hà Giang - Quản Bạ - Đồng Văn - Lũng Cú - Sông Nho Quế",
    description: "Tự hào là nhà tổ chức tour Hà Giang chất lượng số 1 trên thị trường. Hãy đồng hành cùng PYS Travel để có một chuyến đi ấn tượng, vui vẻ, an toàn và đáng nhớ! Mùa xuân Hà Giang là sắc đào sắc mận nở trắng trời, mùa thu là những thửa ruộng bậc thang vàng óng ả, và khi mùa đông đến cả Hà Giang lại chìm trong sắc hồng dịu ngọt của những cánh đồng tam giác mạch mênh mang nơi miền biên viễn.",
    tourCode: "NDHAN200-006-260522XE-V",
    startingGate: "Hà Nội",
    price: "3,790,000",
    startTime: "26/05/2022",
    period: {
      days: "4",
      nights: "3",
    },
    review: "350",
    score: "7.9",
    subtitle: "5 ngày 4 đêm",
    href: "tour-detail",
  },
  {
    id: "4",
    label: "GIA ĐÌNH",
    image: "/Images/tourPage/tourPage4.jpg",
    banner: "/Images/pageBanner/productDetailBanner.jpg",
    title: "Hà Giang - Lũng Cú - Đồng Văn - Nơi đá nở hoa ( Khách sạn 3* & 4*)",
    description: "Tự hào là nhà tổ chức tour Hà Giang chất lượng số 1 trên thị trường. Hãy đồng hành cùng PYS Travel để có một chuyến đi ấn tượng, vui vẻ, an toàn và đáng nhớ! Mùa xuân Hà Giang là sắc đào sắc mận nở trắng trời, mùa thu là những thửa ruộng bậc thang vàng óng ả, và khi mùa đông đến cả Hà Giang lại chìm trong sắc hồng dịu ngọt của những cánh đồng tam giác mạch mênh mang nơi miền biên viễn.",
    tourCode: "NDHAN200-006-260522XE-V",
    startingGate: "Hà Nội",
    price: "3,790,000",
    startTime: "26/05/2022",
    period: {
      days: "4",
      nights: "3",
    },
    review: "300",
    score: "8.0",
    subtitle: "6 ngày 5 đêm",
    href: "tour-detail",
  },
  {
    id: "5",
    label: "TOUR LẺ",
    image: "/Images/tourPage/tourPage5.jpg",
    banner: "/Images/pageBanner/placeDetailBanner.jpg",
    title: "Du lịch Tết Nguyên Đán Hà Nội - Hà Giang - Đồng Văn - Lũng Cú - Cao Bằng - Thác Bản Giốc",
    description: "Tự hào là nhà tổ chức tour Hà Giang chất lượng số 1 trên thị trường. Hãy đồng hành cùng PYS Travel để có một chuyến đi ấn tượng, vui vẻ, an toàn và đáng nhớ! Mùa xuân Hà Giang là sắc đào sắc mận nở trắng trời, mùa thu là những thửa ruộng bậc thang vàng óng ả, và khi mùa đông đến cả Hà Giang lại chìm trong sắc hồng dịu ngọt của những cánh đồng tam giác mạch mênh mang nơi miền biên viễn.",
    tourCode: "NDHAN200-006-260522XE-V",
    startingGate: "Hà Nội",
    price: "2,990,000",
    startTime: "26/05/2022",
    period: {
      days: "4",
      nights: "3",
    },
    review: "350",
    score: "8.5",
  },
  {
    id: "6",
    label: "TRỌN GÓI",
    image: "/Images/tourPage/tourPage6.jpg",
    banner: "/Images/pageBanner/tourDetailBanner.jpg",
    title: "Hà Giang-Lũng Cú - Đồng Văn - Hoa xuân miền Đông Bắc (Sản Phẩm Chọn Lọc, Tiết Kiệm Thời gian)",
    description: "Tự hào là nhà tổ chức tour Hà Giang chất lượng số 1 trên thị trường. Hãy đồng hành cùng PYS Travel để có một chuyến đi ấn tượng, vui vẻ, an toàn và đáng nhớ! Mùa xuân Hà Giang là sắc đào sắc mận nở trắng trời, mùa thu là những thửa ruộng bậc thang vàng óng ả, và khi mùa đông đến cả Hà Giang lại chìm trong sắc hồng dịu ngọt của những cánh đồng tam giác mạch mênh mang nơi miền biên viễn.",
    tourCode: "NDHAN200-006-260522XE-V",
    startingGate: "Hà Nội",
    price: "2,990,000",
    startTime: "26/05/2022",
    period: {
      days: "4",
      nights: "3",
    },
    review: "200",
    score: "8.0",
  },
];

export const hotelData = [
  {
    id: "1",
    label: "HOMESTAY",
    image: "/Images/hotelPage/hotelPage1.jpg",
    banner: "/Images/pageBanner/restaurantDetailBanner.jpg",
    rating: 5,
    title: "Family Homestay Đồng Văn",
    address: "Thôn Đoàn Kết, thị trấn Đồng Văn, huyện Đồng Văn, tỉnh Hà Giang.",
    description:
      "Family Homestay Đồng Văn không nằm ở trung tâm thành phố như Hà Giang Creekside House mà lặng lẽ nép mình ở một thôn nhỏ. Nhưng với vẻ ngoài màu cam rực rỡ, Family Homestay Đồng Văn luôn nổi bật và khác biệt với những ngôi nhà xung quanh.",
    price: "790,000",
    view: 164,
    review: 340,
    score: "8.9",
    href: "hotel-detail",
  },
  {
    id: "2",
    label: "FARMSTAY",
    image: "/Images/hotelPage/hotelPage2.jpg",
    banner: "/Images/pageBanner/productDetailBanner.jpg",
    rating: 5,
    title: "Đồng Quê Homestay Hà Giang",
    address: "Thôn Hạ Thành – Xã Phương Độ, tỉnh Hà Giang",
    description:
      "Đồng Quê Homestay Hà Giang nằm ở giữa chốn rừng xanh bát ngát, thiên nhiên phong cảnh hữu tình, nên thơ, rời xa chốn thành thị tấp nập, phồn hoa. Nếu bạn đã biết đến kiểu kiến trúc nhà sàn của người dân tộc thì Dong Que Homestay Hà Giang cũng có kết cấu tương tự như vậy.",
    price: "450,000",
    view: 164,
    review: 350,
    score: "7.0",
    href: "hotel-detail",
  },
  {
    id: "3",
    label: "HOMESTAY",
    image: "/Images/hotelPage/hotelPage3.jpg",
    banner: "/Images/pageBanner/placeDetailBanner.jpg",
    rating: 5,
    title: "Ban Tuy Homestay",
    address: "Làng văn hóa Du Lịch Bản Tùy, Xã Ngọc Đường, TP. Hà Giang",
    description:
      "Homestay nằm ở Thôn Bản Tùy, xã Ngọc Đường, thành phố Hà Giang với tầm nhìn hướng ra núi non, quang cảnh thiên nhiên kỳ vĩ. Ban Tuy Homestay trang bị đầy đủ, tiện nghi như tivi, quạt, điều hòa, wifi miễn phí.",
    price: "450,000",
    view: 164,
    review: 350,
    score: "7.0",
    href: "hotel-detail",
  },
  {
    id: "4",
    label: "HOTEL",
    image: "/Images/hotelPage/hotelPage4.jpg",
    banner: "/Images/pageBanner/tourDetailBanner.jpg",
    rating: 5,
    title: "Hoang Kim Hotel",
    address:
      "Đường đằng sau bến xe Cầu Mè Đường đằng sau bến xe Cầu Mè, Hà Giang, Việt Nam",
    description:
      "Nằm ở thành phố Hà Giang thuộc tỉnh Hà Giang, Hoang Kim Hotel cung cấp chỗ nghỉ với WiFi miễn phí và chỗ đỗ xe riêng miễn phí. Du khách có thể thư giãn trong vườn của chỗ nghỉ.",
    price: "700,000",
    view: 164,
    review: 350,
    score: "7.5",
    href: "hotel-detail",
  },
  {
    id: "5",
    label: "HOTEL",
    image: "/Images/hotelPage/hotelPage5.jpg",
    banner: "/Images/pageBanner/hotelDetailBanner.jpg",
    rating: 5,
    title: "Mông Lodge Mèo Vạc",
    address:
      "Làng Văn hóa du lịch cộng đồng dân tộc Mông Thôn Pả Vi Hạ, huyện Mèo Vạc, Hà Giang, Việt Nam",
    description:
      "Tọa lạc ở tỉnh Hà Giang, Mông Lodge Mèo Vạc có nhà hàng, xe đạp cho khách sử dụng miễn phí, quán bar và sảnh khách chung.",
    price: "920,000",
    view: 164,
    review: 250,
    score: "7.8",
  },
  {
    id: "6",
    label: "HOMESTAY",
    image: "/Images/hotelPage/hotelPage6.jpg",
    banner: "/Images/pageBanner/restaurantDetailBanner.jpg",
    rating: 5,
    title: "Homestay Nam Tran",
    address: "Thôn Tha, thành phố Hà Giang",
    description:
      "Ở đây có nhiều phòng phù hợp với số lượng người ở. Tất cả các phòng đều được trang bị đầy đủ tivi, wifi miễn phí, quạt, màn chống muỗi, chăn điện sưởi ấm.",
    price: "600,000",
    view: 164,
    review: 340,
    score: "9.0",
  },
];

export const restaurantData = [
  {
    id: "1",
    label: "NHÀ HÀNG",
    image: "/Images/restaurantPage/restaurantPage1.jpg",
    banner: "/Images/pageBanner/restaurantDetailBanner.jpg",
    title: "Quán nhà Sàn cơm dân tộc bản địa",
    address: "18 Nguyễn Văn Linh, TP. Hà Giang",
    description:
      "Nhà hàng chuyên về đồ ăn dân tộc núi rừng như: Rắn 7 món, ba ba, cá tầm, cá nheo sông… Tất cả đều tươi ngon và mang hương vị đặc sắc bởi được chế biến cầu kỳ từ những đầu bếp chuyên nghiệp.",
    view: 164,
    review: 350,
    score: "8.9",
    subtitle: "18 Nguyễn Văn Linh, TP. Hà Giang",
    href: "restaurant-detail",
    price: "3,790,000",
  },
  {
    id: "2",
    label: "NHÀ HÀNG",
    image: "/Images/restaurantPage/restaurantPage2.jpg",
    banner: "/Images/pageBanner/restaurantDetailBanner.jpg",
    title: "Nhà hàng Âu Việt",
    address: "Tổ 3, thị xã Đồng Văn, Đồng Văn, Hà Giang",
    description:
      "Trong các quán ăn ngon ở Hà Giang có Sơn Thủy tại Tổ 1, Phường Quang Trung, khu phố ẩm thực, Thành phố du lịch Hà Giang xứng đáng là nơi ẩm thực ngon.",
    view: 164,
    review: 350,
    score: "7.0",
    subtitle: "Tổ 3, thị xã Đồng Văn, Đồng Văn, Hà Giang",
    href: "restaurant-detail",
    price: "3,790,000",
  },
  {
    id: "3",
    label: "QUÁN ĂN",
    image: "/Images/restaurantPage/restaurantPage3.jpg",
    banner: "/Images/pageBanner/restaurantDetailBanner.jpg",
    title: "Nhà hàng cá Sông Lô",
    address: "Sùng Dúng Lù, P. Quang Trung, TP. Hà Giang",
    description:
      "Địa chỉ quán ăn ngon ở Hà Giang: Tổ I- Phường Nguyễn Trãi-TP.Hà Giang. Nhà hàng Ngói Đỏ có không gian rộng, sức chứa lớn nên thích hợp cho các nhóm người đông, các bữa tiệc tùng, hội họp.",
    view: 164,
    review: 350,
    score: "7.0",
    subtitle: "Sùng Dúng Lù, P. Quang Trung, TP. Hà Giang",
    href: "restaurant-detail",
    price: "3,790,000",
  },
  {
    id: "4",
    label: "NHÀ HÀNG",
    image: "/Images/restaurantPage/restaurantPage4.jpg",
    banner: "/Images/pageBanner/restaurantDetailBanner.jpg",
    title: "Quán ăn ngon Hà Giang Nhà hàng Sơn Thúy",
    address: "161 Trần Hưng Đạo, Trần Phú, TP. Hà Giang",
    description:
      "Đây là quán ăn ngon ở Thành phố Hà Giang. Đến Ngọc Đường, TP.Hà Giang hỏi ai cũng biết. Bởi quan chuyên phục vụ chỉ 2 món: Rau chiên và thịt xiên nướng.",
    view: 164,
    review: 350,
    score: "7.8",
    subtitle: "161 Trần Hưng Đạo, Trần Phú, TP. Hà Giang",
    href: "restaurant-detail",
    price: "3,790,000",
  },
  {
    id: "5",
    label: "NHÀ HÀNG",
    image: "/Images/restaurantPage/restaurantPage5.jpg",
    banner: "/Images/pageBanner/restaurantDetailBanner.jpg",
    title: "Nhà hàng Ngói Đỏ",
    address: "Tổ I- P. Nguyễn Trãi, TP.Hà Giang",
    description:
      "Từng viên bánh được thả vào bát nước ngọt, thơm, ngậy ngậy với nước cốt dừa và gừng. Bánh có vị dẻo thơm của bánh, ngọt ngọt, ngậy ngậy pha chút vị cay nồng ấm.",
    view: 164,
    review: 350,
    score: "9.0",
    subtitle: "Tổ I- P. Nguyễn Trãi, TP.Hà Giang",
    price: "3,790,000",
  },
  {
    id: "6",
    label: "QUÁN ĂN",
    image: "/Images/restaurantPage/restaurantPage6.jpg",
    banner: "/Images/pageBanner/restaurantDetailBanner.jpg",
    title: "Quán ăn ngon Hà Giang bán thắng dền",
    address: "Đến Ngọc Đường, TP.Hà Giang",
    description:
      "Đây là quán ăn ngon Hà Giang tại: 271 Nguyễn Thái Học, P. Trần Phú, Thị Xã Hà Giang.Đến đây bạn nhớ order các món đặc trưng của quán: Phở gà thiến xé, Phở gà thiến chặt miếng, Phở bò tái, chín hay Phở bò sốt vang.",
    view: 164,
    review: 350,
    score: "7.5",
    subtitle: "Đến Ngọc Đường, TP.Hà Giang",
    price: "3,790,000",
  },
];

export const productData = [
  {
    id: "1",
    label: "THỰC PHẨM",
    image: "/Images/productPage/productPage1.jpg",
    banner: "/Images/pageBanner/productDetailBanner.jpg",
    title: "Thịt trâu, lợn gác bếp",
    description:
      "Việc được lai rai món thịt gác bếp dai dai sẽ thật là ngon. Đặc biệt là khi thưởng thức món ăn này lúc nhậu thì ngon tuyệt cú mèo. Bạn sẽ cảm nhận được hương vị thơm ngon của các món thịt gác bếp nơi đây. Rất nhiều du khách đã chọn lựa món ăn đặc sản Hà Giang làm quà này để tặng cho người thân, bạn bè của mình.",
    price: "700,000",
    unit: "kg",
    view: 164,
    review: 350,
    score: "8.9",
    subtitle: "700,000đ",
    href: "product-detail",
  },
  {
    id: "2",
    label: "THỰC PHẨM",
    image: "/Images/productPage/productPage2.jpg",
    banner: "/Images/pageBanner/productDetailBanner.jpg",
    title: "Mật ong bạc hà",
    description:
      "Mật ong bạc hà Hà Giang được biết đến là loại đặc sản quý giá chỉ có tại vùng cao nguyên núi đá Hà Giang. Nếu lần đầu nghe đến mật ong bạc hà Hà Giang thì cùng chúng mình tìm hiểu về loại mật ong đặc sắc này bạn nhé.",
    price: "1,200,000",
    unit: "lít",
    view: 164,
    review: 350,
    score: "7.0",
    subtitle: "1,200,000đ",
    href: "product-detail",
  },
  {
    id: "3",
    label: "NÔNG SẢN",
    image: "/Images/productPage/productPage3.jpg",
    banner: "/Images/pageBanner/productDetailBanner.jpg",
    title: "Cam sành Bắc Quang",
    description:
      "Đã từ lâu, cam sành trở thành một đặc sản nức tiếng mỗi khi người đi xa về gần nhắc đến đất Bắc Quang, thứ đến mới là chè. Có được điều đó là bởi vùng đất này có những điều kiện khí hậu, thổ nhưỡng không giống với bất cứ vùng đất nào để tạo nên những trái cam mang hương vị riêng biệt, vô cùng ngọt ngào và hấp dẫn của miền núi rừng phía nam của tỉnh Hà Giang.",
    price: "200,000",
    unit: "kg",
    view: 164,
    review: 350,
    score: "7.0",
    subtitle: "200,000đ",
    href: "product-detail",
  },
  {
    id: "4",
    label: "QUÀ BIẾU",
    image: "/Images/productPage/productPage5.jpg",
    banner: "/Images/pageBanner/productDetailBanner.jpg",
    title: "Shan tuyết – Chè Hà Giang nổi tiếng",
    description:
      "Đây là loại chè thân gỗ cổ thụ và lá thì mọc theo từng chùm rất độc đáo. Loại chè Hà Giang này rất nổi tiếng và thường được khách du lịch mua về làm quà trong những chuyến đi du lịch tới đây. Khác với các loại chè ở những nơi khác, Shan tuyết lại có hương vị hoàn toàn khác biệt.",
    price: "400,000",
    unit: "100gr",
    view: 164,
    review: 350,
    score: "7.5",
    subtitle: "400,000đ",
    href: "product-detail",
  },
  {
    id: "5",
    label: "BÁNH KẸO",
    image: "/Images/productPage/productPage4.jpg",
    banner: "/Images/pageBanner/productDetailBanner.jpg",
    title: "Bánh tam giác mạch",
    description:
      "Nhắc tới Hà Giang, bạn sẽ không thể bỏ qua món ăn có tên gọi là tam giác mạch. Đây là món ăn ngon mang đậm hương vị của vùng quê nơi đây. Nó được làm từ hạt lúa mạch phơi khô. Sau đó xay ra làm bột.",
    price: "70,000",
    unit: "cái",
    view: 164,
    review: 350,
    score: "9.0",
    subtitle: "70,000đ",
  },
  {
    id: "6",
    label: "THỰC PHẨM",
    image: "/Images/productPage/productPage6.jpg",
    banner: "/Images/pageBanner/productDetailBanner.jpg",
    title: "Lạp xưởng Hà Giang",
    description:
      "Món lạp xưởng tại đây có hương vị hoàn toàn khác biệt so với các nơi khác. Đây là món ăn được người dân vùng núi tự tay làm. Vào mỗi dịp tết đến, người dân nơi đây lại nô nức làm món ăn này bởi đây là dịp tại đây thường diễn ra mổ lợn rất nhiều.",
    price: "700,000",
    unit: "kg",
    view: 164,
    review: 350,
    score: "7.8",
    subtitle: "700,000đ",
  },
];

export const newsData = [
  {
    id: "1",
    image: "/Images/newsCard/newsCard1.jpg",
    banner: "/Images/pageBanner/hotelDetailBanner.jpg",
    userName: "PHƯỢT PRO",
    date: "10.07.2022",
    title: "Kinh nghiệm du lịch Hà Giang 2022 từ A đến Z: di chuyển, lưu trú, ăn chơi, đặc sản...",
    description: "Hà Giang là tỉnh địa đầu của Tổ quốc, phía Đông giáp tỉnh Cao Bằng, phía Tây giáp tỉnh Yên Bái và Lào Cai...",
    price: "3,790,000",
  },
  {
    id: "2",
    image: "/Images/newsCard/newsCard2.jpg",
    banner: "/Images/pageBanner/placeDetailBanner.jpg",
    userName: "KHÁNH TRẦN",
    date: "10.07.2022",
    title: "Năm ngày lang thang Hà Giang - Cao Bằng",
    description: "Lần quay lại Hà Giang này, Ngọc Thảo chọn hành trình kết hợp đi từ cao nguyên đá qua Cao Bằng....",
    price: "3,790,000",
  },
  {
    id: "3",
    image: "/Images/newsCard/newsCard3.jpg",
    banner: "/Images/pageBanner/hotelDetailBanner.jpg",
    userName: "DẤU CHÂN",
    date: "10.07.2022",
    title: "Hoa đào nở muộn ở Hà Giang",
    description: "Đến thôn Vàng Chá Phìn, xã Cao Mã Pờ bạn có cơ hội chiêm ngưỡng sắc hồng của hoa đào nở muộn miền biên giới....",
    price: "3,790,000",
  },
  {
    id: "4",
    image: "/Images/newsCard/newsCard4.jpg",
    banner: "/Images/pageBanner/tourDetailBanner.jpg",
    userName: "HA GIANG TRAVEL",
    date: "10.07.2022",
    title: "Du xuân Hà Giang ở 5 bản làng nguyên sơ",
    description: "Hà Giang là điểm du xuân lý tưởng với nhiều hoạt động như tham quan bản làng, ngắm hoa đào, mận nở và trải nghiệm lễ hội của các dân tộc miền núi....",
    price: "3,790,000",
  },
]
